name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    name: MR check
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.2

      - name: Make gradlew permission executable
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> local.properties

      - name: Install dependencies
        run: ./gradlew clean build --no-daemon

      #     - name: Cache Gradle dependencies
      #       uses: actions/cache@v3
      #       with:
      #         path: |
      #           ~/.gradle/caches
      #           ~/.gradle/wrapper
      #         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      #         restore-keys: |
      #           ${{ runner.os }}-gradle-
      #
      - name: Run Detekt
        run: ./gradlew detekt --no-daemon
