name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    name: MR check
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Install dependencies
        run: ./gradlew clean build --no-daemon

      - name: Run Detekt
        run: ./gradlew detekt --no-daemon
